# Generated by Django 3.0.9 on 2021-06-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='portfolio',
        ),
    ]
